exclude: ['vendor']
include: ['_pages', '_pages/film', '_pages/writing', 'pages/photography']

title:            San Francisco Bootblack
email:            producer@sanfranciscobootblack.com
url:              http://www.sanfranciscobootblack.com
paginate:         1
author:
  name:           San Francisco Bootblack Producers
  url:            http://www.sanfranciscobootblack.com
  email:          producer@sanfranciscobootblack.com
  twitter:        https://twitter.com/twidx

# Site settings
description: > # this means to ignore newlines until "baseurl:"
  The San Francisco Bootblack contest will be held as part of the Leather Alliance Weekend 2018
  along side the Mr San Francisco Leather Contest.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.sanfranciscobootblack.com" # the base hostname & protocol for your site
# twitter_username: twidx
# github_username:  tkwidmer

tag_page: '/blog/tags/'
category_page: '/blog/categories/'

collections:
  galleries:
    output: true

# Build settings
pages: ./_pages
markdown: kramdown

# pages_list:
#   Programming: '/pages/programming.html'
#   Speaking:   '/pages/speaking.html'
#   Blog: '/blog.html'
#   Feed: '/feed.xml'

# social_links:
#   - icon: fa-twitter
#     url: http://www.twitter.com/twidx
#   - icon: fa-github
#     url: http://www.github.com/tkwidmer

gems:
  - jekyll-redirect-from

header-img: "images/sf1.jpg"
